package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class DartIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, DartIcons.class);
  }

  public static final Icon DartLang = load("/icons/dartLang.png"); // 16x16
  public static final Icon Dart = load("/icons/dart.png"); // 16x16
  public static final Icon DartTest = load("/icons/dart_test.png"); // 16x16
  public static final Icon Label = load("/icons/label.png"); // 16x16
}
