package icons;

import javax.swing.Icon;

import com.intellij.icons.AllIcons;
import com.intellij.openapi.util.IconLoader;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class DartIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, DartIcons.class);
  }

  public static final Icon Annotationtype_dart = AllIcons.Nodes.Annotationtype;
  public static final Icon Class_dart =  AllIcons.Nodes.Class;
  public static final Icon Dart_16 = load("/dart_16.png"); // 16x16
  public static final Icon Dart_24 = load("/dart_24.png"); // 24x24
  public static final Icon Field_dart = AllIcons.Nodes.Field;
  public static final Icon Function_dart = AllIcons.Nodes.Function;
  public static final Icon Interface_dart = AllIcons.Nodes.Interface;
  public static final Icon Label_dart = load("/label_dart.png"); // 16x16
  public static final Icon Method_dart = AllIcons.Nodes.Method;
  public static final Icon Parameter_dart = AllIcons.Nodes.Parameter;
  public static final Icon Variable_dart = AllIcons.Nodes.Variable;
}
