package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class DartIcons {
  private static Image load(String path) {
    return IconLoader.getIcon(path, DartIcons.class);
  }

  public static final Image DartLang = load("/icons/dartLang.png"); // 16x16
  public static final Image Dart = load("/icons/dart.png"); // 16x16
  public static final Image DartTest = load("/icons/dart_test.png"); // 16x16
  public static final Image Label = load("/icons/label.png"); // 16x16
}
